name: Deploy Uptime Kuma

on:
  push:
    branches: [main]
    paths:
      - "uptime-kuma-values.yaml"
      - ".github/workflows/deploy-uptime-kuma.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_DEV }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          # Ensure kubeconfig is applied
          cat $PWD/kubeconfig
          # Set the context if needed
          kubectl config use-context do-blr1-accuknox-dev
          kubectl get nodes  # This ensures kubectl can access the cluster

      - name: Add Helm repo
        run: |
          helm repo add uptime-kuma https://dirsigler.github.io/uptime-kuma-helm
          helm repo update

      - name: Deploy Uptime Kuma
        run: |
          helm upgrade --install uptime-kuma uptime-kuma/uptime-kuma \
            --namespace uptime-kuma \
            --create-namespace \
            -f uptime-kuma-values.yaml
